### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by sam123127** [sam123127/Server#1]
The client-server code needs improvements for better reliability and scalability. Currently, it has issues with IP resolution and lacks proper error handling, leading to crashes when the server is unavailable. Additionally, the server doesn’t handle graceful shutdowns. We aim to replace IP resolution with localhost, add error handling, and implement a graceful shutdown mechanism to make the code more robust and maintainable for future contributions.

**Comment by sudarshandongre** [comment]
The issue with the client-server connection has been resolved. I updated the code to use localhost for more reliable IP resolution and added error handling for connection failures. Additionally, the server now supports graceful shutdown with KeyboardInterrupt. These improvements have been tested locally and should resolve the connection issues you encountered. Please review the changes in the associated pull request.

**Comment by sam123127** [comment]
Thank You For your Hard Work
